name: flutter_deck_example
description: An example presentation created using flutter_deck.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  cupertino_icons: ^1.0.2
  file: ^7.0.1
  file_saver: ^0.3.1
  flutter:
    sdk: flutter
  flutter_deck: ^0.23.0+1
  flutter_deck_pptx_export: ^0.1.0
  flutter_deck_web_client: ^0.4.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
