name: flutter_deck
description: A lightweight, customizable, and easy-to-use framework to create presentations in Flutter.
version: 0.27.0
resolution: workspace
homepage: https://github.com/mkobuolys/flutter_deck
repository: https://github.com/mkobuolys/flutter_deck/tree/main/packages/flutter_deck
issue_tracker: https://github.com/mkobuolys/flutter_deck/issues
topics:
  - flutterdeck
  - presentation
  - slides
screenshots:
  - description: The flutter_deck package header image.
    path: screenshots/header.png
funding:
  - https://github.com/sponsors/mkobuolys

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  auto_size_text: ^3.0.0
  diff_match_patch: ^0.4.1
  flutter:
    sdk: flutter
  flutter_deck_client: ^0.3.0
  go_router: ^17.1.0
  syntax_highlight: ^0.5.0
  web: ^1.1.1
  window_manager: ^0.5.1

dev_dependencies:
  build_runner: ^2.11.1
  fake_async: ^1.3.3
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^5.6.3
flutter:
  uses-material-design: true

  assets:
    - assets/
