name: flutter_deck_ws_client
description: A WebSocket client for the flutter_deck package that allows you to control the presentation remotely.
version: 0.3.0
resolution: workspace
homepage: https://github.com/mkobuolys/flutter_deck
repository: https://github.com/mkobuolys/flutter_deck/tree/main/packages/flutter_deck_ws_client
issue_tracker: https://github.com/mkobuolys/flutter_deck/issues
topics:
  - flutterdeck
  - presentation
  - slides
funding:
  - https://github.com/sponsors/mkobuolys

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter_deck_client: ^0.3.0
  web_socket_client: ^0.2.1

dev_dependencies:
  test: ^1.25.8
